version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  debian: &debian
    image: jancajthaml/debian-packager
    tty: true
    volumes:
      - .:/project
    working_dir: /project

  # -------------------------------------------------------------------------- #

  release:
    <<: *debian
    entrypoint:
      - /project/dev/lifecycle/release

  # -------------------------------------------------------------------------- #

  debian-package:
    <<: *debian
    entrypoint:
      - /project/dev/lifecycle/debian

# ---------------------------------------------------------------------------- #
