version: 2.1

# ---------------------------------------------------------------------------- #

workflows:

  version: 2

  tag:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - versions:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-debian-amd64:
          requires:
            - checkout
            - versions
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-debian-armhf:
          requires:
            - checkout
            - versions
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-debian-arm64:
          requires:
            - checkout
            - versions
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-docker:
          requires:
            - package-debian-amd64
            - package-debian-armhf
            - package-debian-arm64
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - release:
          requires:
            - package-docker
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

  commit:
    jobs:
      - checkout
      - versions
      - package-debian-amd64:
          requires:
            - checkout
            - versions
      - package-debian-armhf:
          requires:
            - checkout
            - versions
      - package-debian-arm64:
          requires:
            - checkout
            - versions
      - package-docker:
          requires:
            - package-debian-amd64
            - package-debian-armhf
            - package-debian-arm64

# ---------------------------------------------------------------------------- #

executors:

  git:
    docker:
      - image: docker.io/alpine/git

  go:
    docker:
      - image: docker.io/jancajthaml/go:latest

  debian:
    docker:
      - image: docker.io/jancajthaml/debian-packager:latest

  machine:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: false

# ---------------------------------------------------------------------------- #

jobs:

  # -------------------------------------------------------------------------- #

  checkout:
    executor: git
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - save_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /mnt/ramdisk/.git
            - /mnt/ramdisk/dev
            - /mnt/ramdisk/packaging
            - /mnt/ramdisk/Dockerfile

  # -------------------------------------------------------------------------- #

  versions:
    executor: git
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - run:
          name: Update VERSION + META
          command: |
            if [ -z ${CIRCLE_TAG} ] ; then
              tags=$(git tag --sort=-v:refname | head -1)
              if [ -z ${tags} ] ; then
                VERSION=v0.0.0
              else
                VERSION=${tags}
              fi
              META=$(echo -e ${CIRCLE_BRANCH} | sed 's:.*/::')
              echo -e "${VERSION#v}" > /mnt/ramdisk/VERSION
              echo -e "${META}" > /mnt/ramdisk/META
            else
              echo -e "${CIRCLE_TAG#v}" > /mnt/ramdisk/VERSION
              echo -e "main" > /mnt/ramdisk/META
            fi
      - save_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /mnt/ramdisk/VERSION
            - /mnt/ramdisk/META

  # -------------------------------------------------------------------------- #

  package-debian-amd64:
    executor: debian
    working_directory: /mnt/ramdisk
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Package for debian
          command: |
            VERSION=$(cat /mnt/ramdisk/VERSION)
            /mnt/ramdisk/dev/lifecycle/debian \
              --arch amd64 \
              --pkg metrics \
              --version ${VERSION} \
              --source /mnt/ramdisk/packaging
          no_output_timeout: 5m
      - save_cache:
          key: debian-amd64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /mnt/ramdisk/packaging/bin

  # -------------------------------------------------------------------------- #

  package-debian-armhf:
    executor: debian
    working_directory: /mnt/ramdisk
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Package for debian
          command: |
            VERSION=$(cat /mnt/ramdisk/VERSION)
            /mnt/ramdisk/dev/lifecycle/debian \
              --arch armhf \
              --pkg metrics \
              --version ${VERSION} \
              --source /mnt/ramdisk/packaging
          no_output_timeout: 5m
      - save_cache:
          key: debian-armhf-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /mnt/ramdisk/packaging/bin

  # -------------------------------------------------------------------------- #

  package-debian-arm64:
    executor: debian
    working_directory: /mnt/ramdisk
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Package for debian
          command: |
            VERSION=$(cat /mnt/ramdisk/VERSION)
            /mnt/ramdisk/dev/lifecycle/debian \
              --arch arm64 \
              --pkg metrics \
              --version ${VERSION} \
              --source /mnt/ramdisk/packaging
          no_output_timeout: 5m
      - save_cache:
          key: debian-arm64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /mnt/ramdisk/packaging/bin

  # -------------------------------------------------------------------------- #

  package-docker:
    docker:
      - image: docker.io/docker:18.06.0-ce-git
    working_directory: /mnt/ramdisk
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-amd64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-armhf-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-arm64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Package for docker
          command: |
            VERSION=$(cat /mnt/ramdisk/VERSION)
            META=$(cat /mnt/ramdisk/META)

            docker build \
              -t docker.io/openbank/metrics:v${VERSION}-${META} \
              -f packaging/docker/Dockerfile \
              .
            docker build \
              -t docker.pkg.github.com/jancajthaml-openbank/metrics/metrics:${VERSION} \
              -f packaging/docker/Dockerfile \
              .
      - run:
          name: Publish to docker.io
          command: |
            echo ${DOCKER_PASSWORD} \
              | docker login -u ${DOCKER_USER} --password-stdin
            VERSION=$(cat /mnt/ramdisk/VERSION)
            META=$(cat /mnt/ramdisk/META)
            docker push \
              docker.io/openbank/metrics:${VERSION}-${META}
            rm -f /root/.docker/config.json
      - run:
          name: Publish to docker.pkg.github.com
          command: |
            echo ${GITHUB_RELEASE_TOKEN} \
              | docker login docker.pkg.github.com -u jancajthaml --password-stdin
            VERSION=$(cat /mnt/ramdisk/VERSION)
            docker push \
              docker.pkg.github.com/jancajthaml-openbank/metrics/metrics:${VERSION}
            rm -f /root/.docker/config.json

  # -------------------------------------------------------------------------- #

  release:
    executor: debian
    working_directory: /mnt/ramdisk
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-amd64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-armhf-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-arm64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - deploy:
          name: Release artifacts to github
          command: |
            /mnt/ramdisk/dev/lifecycle/release \
              --version ${CIRCLE_TAG} \
              --token ${GITHUB_RELEASE_TOKEN}

# ---------------------------------------------------------------------------- #
