version: 2.1

# ---------------------------------------------------------------------------- #

workflows:

  version: 2

  tag:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - versions:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-debian-amd64:
          requires:
            - checkout
            - versions
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-debian-arm64:
          requires:
            - checkout
            - versions
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-docker:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - package-debian-amd64
            - package-debian-arm64
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - release:
          requires:
            - package-docker
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

  commit:
    jobs:
      - checkout
      - versions
      - package-debian-amd64:
          requires:
            - checkout
            - versions
      - package-debian-arm64:
          requires:
            - checkout
            - versions
      - package-docker:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - package-debian-amd64
            - package-debian-arm64

# ---------------------------------------------------------------------------- #

executors:

  git:
    docker:
      - image: docker.io/alpine/git

  go:
    docker:
      - image: docker.io/jancajthaml/go:latest

  debian:
    docker:
      - image: docker.io/jancajthaml/debian-packager:latest

  machine-arm64:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: false
      resource_class: arm.medium

  machine-amd64:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: false
      resource_class: medium

# ---------------------------------------------------------------------------- #

jobs:

  # -------------------------------------------------------------------------- #

  checkout:
    executor: git
    working_directory: /home/circleci/project
    steps:
      - checkout
      - save_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/project/.git
            - /home/circleci/project/dev
            - /home/circleci/project/packaging
            - /home/circleci/project/Dockerfile

  # -------------------------------------------------------------------------- #

  versions:
    executor: git
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Update VERSION + META
          command: |
            if [ -z ${CIRCLE_TAG} ] ; then
              tags=$(git tag --sort=-v:refname | head -1)
              if [ -z ${tags} ] ; then
                VERSION=v0.0.0
              else
                VERSION=${tags}
              fi
              META=$(echo -e ${CIRCLE_BRANCH} | sed 's:.*/::')
              echo -e "${VERSION#v}" > /home/circleci/project/VERSION
              echo -e "${META}" > /home/circleci/project/META
            else
              echo -e "${CIRCLE_TAG#v}" > /home/circleci/project/VERSION
              echo -e "main" > /home/circleci/project/META
            fi
      - save_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/project/VERSION
            - /home/circleci/project/META

  # -------------------------------------------------------------------------- #

  package-debian-amd64:
    executor: debian
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Package for debian
          command: |
            VERSION=$(cat /home/circleci/project/VERSION)
            /home/circleci/project/dev/lifecycle/debian \
              --arch amd64 \
              --pkg metrics \
              --version ${VERSION} \
              --source /home/circleci/project/packaging
          no_output_timeout: 5m
      - save_cache:
          key: debian-amd64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/project/packaging/bin

  # -------------------------------------------------------------------------- #

  package-debian-arm64:
    executor: debian
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Package for debian
          command: |
            VERSION=$(cat /home/circleci/project/VERSION)
            /home/circleci/project/dev/lifecycle/debian \
              --arch arm64 \
              --pkg metrics \
              --version ${VERSION} \
              --source /home/circleci/project/packaging
          no_output_timeout: 5m
      - save_cache:
          key: debian-arm64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/project/packaging/bin

  # -------------------------------------------------------------------------- #

  package-docker:
    parameters:
      arch:
        type: string
    executor: machine-<< parameters.arch >>
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: binaries-<< parameters.arch >>-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-<< parameters.arch >>-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Publish << parameters.arch >> to docker.io
          command: |
            export VERSION=$(cat /home/circleci/project/VERSION)
            export META=$(cat /home/circleci/project/META)
            export ARCH=<< parameters.arch >>

            docker build \
              -t docker.io/openbank/metrics:${ARCH}-${VERSION}.${META} \
              -f ./packaging/docker/${ARCH}/Dockerfile .

            echo ${DOCKER_PASSWORD} | docker login docker.io -u ${DOCKER_USER} --password-stdin

            docker push docker.io/openbank/metrics:${ARCH}-${VERSION}.${META}

            rm -f /home/circleci/.docker/config.json
      - run:
          name: Publish << parameters.arch >> to docker.pkg.github.com
          command: |
            export VERSION=$(cat /home/circleci/project/VERSION)
            export ARCH=<< parameters.arch >>

            docker build \
              -t docker.pkg.github.com/jancajthaml-openbank/metrics/metrics:${ARCH}-${VERSION} \
              -f ./packaging/docker/${ARCH}/Dockerfile .

            echo ${GITHUB_RELEASE_TOKEN} | docker login docker.pkg.github.com -u ${DOCKER_USER} --password-stdin

            docker push docker.pkg.github.com/jancajthaml-openbank/metrics/metrics:${ARCH}-${VERSION}

            rm -f /home/circleci/.docker/config.json

  # -------------------------------------------------------------------------- #

  release:
    executor: debian
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-amd64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: debian-arm64-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - deploy:
          name: Release artifacts to github
          command: |
            /home/circleci/project/dev/lifecycle/release \
              --version ${CIRCLE_TAG} \
              --token ${GITHUB_RELEASE_TOKEN}

# ---------------------------------------------------------------------------- #
