.nh
.TH "LAKE" "1" "Jul 2021" "Metrics" "OpenBank Metrics Manual"
.sp
.SH "NAME"
metrics \- starts openbank metrics daemon
.SH "SYNOPSIS"
.sp
.nf
\fIlake
.fi
.sp
.SH "DESCRIPTION"
.sp
The metrics daemon collects metrics for openbank services.
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
